Fix proposal element outside `<Icon />` component from a div to a span.
voyagegroup/ingred-ui pull request #1004
Opened 2022-09-25 23:54 UTC by takurinton

ingred-ui 内でも存在するが、コードを書いてるとために `<Icon />` を button で囲いたくなる時がある。

mdn の [button のリファレンス](https://developer.mozilla.org/ja/docs/Web/HTML/Element/button) を見てみると、

許可されている内容	| [記述コンテンツ](https://developer.mozilla.org/ja/docs/Web/Guide/HTML/Content_categories#%E8%A8%98%E8%BF%B0%E3%82%B3%E3%83%B3%E3%83%86%E3%83%B3%E3%83%84)、但し[対話型コンテンツ](https://developer.mozilla.org/ja/docs/Web/Guide/HTML/Content_categories#%E5%AF%BE%E8%A9%B1%E5%9E%8B%E3%82%B3%E3%83%B3%E3%83%86%E3%83%B3%E3%83%84)があってはならない
-- | --

とある。
記述コンテンツには `<div>` は含まれないので、これを `<span>` に変更をした。
https://developer.mozilla.org/ja/docs/Web/Guide/HTML/Content_categories#%E8%A8%98%E8%BF%B0%E3%82%B3%E3%83%B3%E3%83%86%E3%83%B3%E3%83%84

`<div>` と `<span>` の互換を取るために `display: block;` を追加した。

2022-09-26 00:02 UTC, takurinton commented
チームメンションって全員にレビュー飛ぶんじゃなくてランダムで選ぶ感じなんですね

2022-09-26 00:04 UTC, takurinton commented
げ、こんな依存してるのかよ
![image](https://user-images.githubusercontent.com/50351271/192171747-313f7205-710f-4f26-8d6a-d7c8ecf78954.png)

2022-09-26 00:06 UTC, takurinton commented
一旦コミットします、もしおかしかったら閉じるか revert すればいいので

2022-09-26 03:56 UTC, takurinton commented on src/components/Icon/styled.ts
> +  display: block;
snapshot の diff が多すぎてわかりにくいけど、変更したのはここだけ

2022-09-27 08:44 UTC, maktak1995 approved these changes
![LGTM](https://image.lgtmoon.dev/35008)

2022-09-27 13:11 UTC, penicillin0 requested changes
https://github.com/voyagegroup/ingred-ui/blob/cb3704140075cb701db217434c0ec4850edf04e7/src/components/Icon/Icon.tsx#L263

そうなると`HTMLDivElement`は`HTMLSpanElement`が正しい？

2022-09-27 19:38 UTC, takurinton commented
@penicillin0 
oops、抜けがあった、あざますmm

2022-09-27 22:41 UTC, penicillin0 approved these changes
LGTM!!!!

2022-09-28 01:45 UTC, youchann approved these changes

2022-09-28 22:14 UTC, takurinton commented
MEMO:
- [mui の SvgIcon](https://github.com/mui/material-ui/blob/master/packages/mui-joy/src/SvgIcon/SvgIcon.tsx#L26-L55) は外枠は svg
- [chakra-ui の <Icon />](https://github.com/chakra-ui/chakra-ui/blob/main/packages/components/icon/src/icon.tsx#L74-L85) も svg

2022-09-29 01:07 UTC, takurinton commented
本来であれば svg を返すようなコンポーネントを実装したいけど、一旦この状態で取り込みます。

2022-09-29 01:08 UTC, merged