MultipleFilterの入力ステップをスキップしたい
voyagegroup/ingred-ui pull request #1646
Opened 2024-07-11 01:44 UTC by trailstem

## 今回実現したいこと
- オプションでセクションを選択せず、直接コンディションを入力できるようにしたい。
- カテゴリ選択で表示されるPopoverが選択肢を選択せずとも閉じるようにしたい。
- 選択後のフィルター条件を見やすく「hoge: **fuga**」の形式で表示したい。

## Check List (If️ you added new component in this PR)
- [ ] Export the component in `src/components/index.ts`
- [ ] Add example to `.storybook/documents/Information/Samples/Samples.stories.tsx`
- [ ] Localize added component

2024-07-11 08:32 UTC, deatiger reviewed
@trailstem 
口頭でも話した通り、stories にスキップする場合の例を追加するのも対応お願いします！

2024-07-11 08:32 UTC, deatiger commented on src/components/MultipleFilter/types/index.ts
> +  skipFilterSection?: boolean;
- boolean かわかるような命名にしたい
- FilterSection という言葉はどこにも使われていないので変えたい（が、そもそもの実装から命名ずれているのでどうしようかな... `shouldSkipConditionSelecting` か `shouldSkipFilterSelecting` か...

2024-07-17 08:44 UTC, trailstem commented on src/components/MultipleFilter/MultipleFilter.tsx
> +          } else {
@deatiger 
ステップをスキップするので「`type = text`」の場合は`filters`要素が1つのみを想定していませんが、「`type = boolean`」を使用する場合は、filtersに要素2つを使用しないといけないです。
全てのfitlerを選択した上で初めて「`type = boolean`」と設定したCategoryが選択できなくなる挙動だったので、スキップフラグがある時点で選択できないように修正

2024-07-17 09:37 UTC, deatiger reviewed
@trailstem 
そもそもの実装が絶妙なのもあり、コードからだけでは実装意図を把握するのが難しいので、明日ペアプロさせてください！

2024-07-18 02:03 UTC, deatiger reviewed
@trailstem 
ペアプロで会話した内容をコメントしておきました！

2024-07-18 02:03 UTC, deatiger commented on src/components/MultipleFilter/types/index.ts
> +  shouldSkipConditionSelecting?: boolean;
boolean では持たずに filters.length === 1 ならばスキップする、という挙動にしたほうがシンプルそう。

2024-07-18 02:03 UTC, deatiger commented on src/components/MultipleFilter/internal/Label/Label.tsx
> +          {`${filter.filterName}:`}
```suggestion
          {filter.filterName}:
```

2024-07-18 02:03 UTC, deatiger commented on src/components/MultipleFilter/internal/FilterCard/FilterCard.tsx
> +      filterType: filter?.control.type as Types,
`selectedFilterPack.filters.length === 1` ならば `selectedFilter` の初期値を `selectedFilterPack.filters[0]` とすることで、ここの条件分岐は不要になりそう。

2024-07-18 02:03 UTC, deatiger commented on src/components/MultipleFilter/internal/FilterCard/FilterCard.tsx
> +      );
変更しなくて良さそう

2024-07-18 02:03 UTC, deatiger commented on src/components/MultipleFilter/internal/EditFilterCard/EditFilterCard.tsx
> +      );
変更しなくて良さそう

2024-07-18 02:03 UTC, deatiger commented on src/components/MultipleFilter/MultipleFilter.tsx
> +          } else {
> ステップをスキップするので「type = text」の場合はfilters要素が1つのみを想定していませんが、「type = boolean」を使用する場合は、filtersに要素2つを使用しないといけないです。

この前提が間違っていそう

2024-07-18 08:13 UTC, trailstem commented on src/components/MultipleFilter/MultipleFilter.tsx
> +        }
@deatiger 
選択肢をスキップする場合、MultipleFilterに渡す`filters`の`filterName`は入力想定でないためblankを想定。
その際、選択済みの値`referredFilter`とユーザー側で設定する`filterPack`のfilterNameに差異が発生する。
EditFilterCardに渡す`selectedFilterPack`のfilterNameがblankで設定され、[該当箇所](https://github.com/voyagegroup/ingred-ui/blob/26f7a237cfe13ef5f57370015d4737b4f166296b/src/components/MultipleFilter/internal/EditFilterCard/EditFilterCard.tsx#L57)で返却される`filter`が設定されず、[入力項目箇所](https://github.com/voyagegroup/ingred-ui/blob/26f7a237cfe13ef5f57370015d4737b4f166296b/src/components/MultipleFilter/internal/EditFilterCard/EditFilterCard.tsx#L167)が表示されずキャプチャのようになってしまうため、スキップ時はcategoryNameを設定しました！
![スクリーンショット 2024-07-18 16 50 00](https://github.com/user-attachments/assets/419206bc-4c99-4562-a277-aef8a204d7e0)

2024-07-18 08:13 UTC, trailstem commented on src/components/MultipleFilter/internal/FilterCard/FilterCard.tsx
> +    (isMultipleFilters && !isSectionSelected) || !isConditionSet;
既存コード（以下）に加え、filters.lengthの条件が加わった際に可読性悪くなるので変数で定義しました。
```tsx
disabled={!section || !condition}
```

2024-07-18 09:59 UTC, deatiger requested changes
@trailstem

2024-07-18 09:59 UTC, deatiger commented on src/components/MultipleFilter/internal/EditFilterCard/EditFilterCard.tsx
> +          selectedFilterPack?.filters.length > 1 && (
nits
```suggestion
        {(selectedFilterPack?.filters?.length ?? 0) > 1 && (
```

2024-07-18 09:59 UTC, deatiger commented on src/components/MultipleFilter/internal/FilterCard/FilterCard.tsx
> +  const isMultipleFilters = selectedFilterPack?.filters.length !== 1;
厳密にはこっちじゃないかな。
```suggestion
  const isMultipleFilters = selectedFilterPack?.filters.length > 1;
```

2024-07-18 09:59 UTC, deatiger commented on src/components/MultipleFilter/internal/FilterCard/FilterCard.tsx
> +          selectedFilterPack.filters.length > 1 && (
この条件式ってつまり isMultipleFilters じゃないですか？

2024-07-18 09:59 UTC, deatiger commented on src/components/MultipleFilter/internal/FilterCard/FilterCard.tsx
> +    (isMultipleFilters && !isSectionSelected) || !isConditionSet;
1箇所でしか参照されていない boolean なので変数化する必要がないように思いました。
また、変数名が増えるとコンテキストが増えるので、逆に難しくなるような気がします。
isApplyButtonDisabled って何？ → isMultipleFilters  と isSectionSelected と isConditionSet って何？ → section と condition って何？のように、、（これは感覚的な問題かもしれない）

2024-07-18 09:59 UTC, deatiger commented on src/components/MultipleFilter/internal/FilterCard/FilterCard.tsx
> +      : undefined,
これもつまり isMultipleFilters なのではと思いましたがどうでしょう？
（ isMultipleFilters を先に宣言する必要ありますが）
```suggestion
    isMultipleFilters
      ? undefined
      : selectedFilterPack.filters[0]
```

2024-07-18 09:59 UTC, deatiger commented on src/components/MultipleFilter/internal/FilterCard/FilterCard.tsx
> +      : undefined,
ちなみに万が一 filters が0件の場合は結果的に undefined が初期値になる

2024-07-19 04:59 UTC, deatiger approved these changes
@trailstem 
変更については LGTM です！
patch じゃなくて minor にしてもらえればOKです

2024-07-19 04:59 UTC, deatiger commented on .changeset/red-peas-prove.md
@trailstem 
今回の変更は、後方互換性を保ちつつ機能追加しているので、マイナーバージョンかな。
https://semver.org/lang/ja/#spec-item-7

2024-07-19 06:26 UTC, noronaoki commented
@trailstem LGTM!!

2024-07-19 06:41 UTC, merged