表示順序など大枠の完成
voyagegroup/ingred-ui pull request #258
Opened 2021-03-17 08:19 UTC by penicillin0

## やったこと
- Multiple Filterの大枠(一通りの表示)の作成

## Attention

多くを`TODO`で捌けてあります。
`TODO`以外の部分に関して、表示のロジックと挙動、styleらへんを見ていただければと思います。

## ref
- [issue](https://github.com/voyagegroup/fluct_XDC/issues/106)
- [xd](https://xd.adobe.com/view/a2977fa3-990f-4e0b-7eb7-1f835cc8c42a-d4a6/screen/f3d45175-f589-4791-83bf-d823c1677cff/)

2021-03-18 07:22 UTC, ryokosuge requested changes
確認お願いしますー！

2021-03-18 07:22 UTC, ryokosuge commented on src/components/MultipleFilter/MultipleFilter.tsx
> +  const handleSlect = (elem: any) => () => {
`handleSelect` かな？

2021-03-18 07:22 UTC, ryokosuge commented on src/components/MultipleFilter/MultipleFilter.tsx
> +  const handleSlect = (elem: any) => () => {
あーあとここの引数のanyは型指定できないんだっけ？？

2021-03-18 07:22 UTC, ryokosuge commented on src/components/MultipleFilter/MultipleFilter.tsx
> +      <Styled.Container isFocused={step !== 0}>
dom内で式を書くのはよろしくないかな、条件式変わることもあるだろうからfunctionにしたほうが良さそう

2021-03-18 07:22 UTC, ryokosuge commented on src/components/MultipleFilter/MultipleFilter.tsx
> +      {step === 2 && (
ここの `step ===` も不思議でレビューしてる側からすると、stepがいくつあって2がどの段階だか読んでもわからないので定数化なりenum化なりしてほしいところ！
マジックナンバー感が漂ってきました

2021-03-18 07:40 UTC, penicillin0 commented on src/components/MultipleFilter/MultipleFilter.tsx
> +  const handleSlect = (elem: any) => () => {
@ryokosuge 
指定できそうですが、`elem`の型をこれから考えるつもりだったので、`any`にしてました
！

2021-03-22 05:52 UTC, penicillin0 commented
メモ
```
  条件
  0(Defalut):
    selectedFilter === null
    focusされていない状態
  1(FilterSelect):
    selectedFilter === null
    focusされている状態
  2(ConditionSelect):
    selectedFilter !== null
    focusされている状態
```

2021-03-22 05:56 UTC, penicillin0 commented on src/components/MultipleFilter/MultipleFilter.tsx
> +}
クラスに対して、
- focusしているか
- filterがセットされているか
を与えれば状態が返ってくるようにしました。

2021-03-22 05:58 UTC, penicillin0 commented on src/components/MultipleFilter/MultipleFilter.tsx
> +  }, [isFocus, selectedFilter]);
ここで状態の変更を検知しています。

途中で抜けた場合もクラス内で管理したかったのですが、setStateがクラス内ではスコープ外なのでここでチェックしています。

2021-03-22 05:58 UTC, penicillin0 commented on src/components/MultipleFilter/MultipleFilter.tsx
> +  const handleSelect = (elem: any) => () => {
elemの型は別のPRで考えようと思っています。

2021-03-24 02:07 UTC, penicillin0 commented on src/components/MultipleFilter/MultipleFilter.tsx
> +    return Status.Empty;
ここに到達することはないのですが、returnが無い、と怒られてしまうので入れています。

2021-03-24 02:08 UTC, penicillin0 commented on src/components/MultipleFilter/MultipleFilter.tsx
> +    return Status.Empty;
ここに到達することはないのですが、
> 関数に終了の return ステートメントがないため、戻り値の型には 'undefined' が含まれません。ts(2366)

となってしまうので入れています。

2021-03-24 04:10 UTC, ryokosuge commented on src/components/MultipleFilter/MultipleFilter.tsx
> +    return Status.Empty;
```typescript
if (selectedFilter === null) {
  return Status.FilterSelecting;
}

if (selectedFilter !== null) {
  return Status.ConditionSelecting;
}
```

1つ目のifの評価式で `selectedFilter` がnullじゃないことは証明されてるからいらなそう！
引数は今後変わるからanyにしてるんだろうなと信じます！

2021-03-24 04:13 UTC, ryokosuge commented on src/components/MultipleFilter/MultipleFilter.tsx
> +        isFocused={getCurrentStatus(isFocus, selectedFilter) !== Status.Empty}
```typescript
getCurrentStatus(isFocus, selectedFilter)
```

これ、下でも毎回実行した後にStatusチェックしてるように見えるんだけど、これ1回にまとめられないかな？？

```typescript
const currentStatus = getCurrentStatus(isFocus, selectedFilter)
const isFocused = currentStatus !== Status.Empty
```

2021-03-24 04:15 UTC, ryokosuge commented on src/components/MultipleFilter/MultipleFilter.tsx
> +};
ここを `MultipleFilter.tsx` に書くと今後拡張していくとcomponentクラスのファイルが大きくなるので、別ファイルにまとめて欲しいな！

`MultipleFilterStatus.ts` かなー

2021-03-24 04:41 UTC, penicillin0 commented on src/components/MultipleFilter/MultipleFilter.tsx
> +};
@ryokosuge 

https://github.com/voyagegroup/ingred-ui/blob/b2bea16081b16d0495fcf08cdf772e6415eb3c42/src/components/MultipleFilter/MultipleFilter.tsx#L11-L17

じゃなくてですか？

2021-03-24 04:41 UTC, ryokosuge commented on src/components/MultipleFilter/MultipleFilter.tsx
> +};
ごめん、そこでした！（何故だ

2021-03-24 04:48 UTC, penicillin0 commented
@ryokosuge 
修正しました！
お願いしますmm

2021-03-24 04:53 UTC, ryokosuge commented on src/components/MultipleFilter/MultipleFilter.tsx
> +    return Status.Empty;
ここの処理も `MultipeFilterStatus.ts` に含めちゃっていいんじゃない？？

2021-03-24 05:01 UTC, penicillin0 commented on src/components/MultipleFilter/MultipleFilter.tsx
> +    return Status.Empty;
@ryokosuge 
status関連はここに切り出した方が良さそうですね！
修正しました！

2021-03-24 05:07 UTC, ryokosuge approved these changes
LGTM 👍

2021-03-24 05:46 UTC, maktak1995 approved these changes

2021-03-29 06:30 UTC, merged