MenuにWarnTextを追加
voyagegroup/ingred-ui pull request #288
Opened 2021-04-08 04:51 UTC by hirokikondo86

# Ref
[PR#287](https://github.com/voyagegroup/ingred-ui/pull/287)

## やったこと
- [x] `disabled?: boolean` を削除
- [x] `type: "default" | warning" | "disabled"` を追加
- [x] `type: "default"`でデフォルト、`type: "warning"` で WarnText 、`type: "disabled"` で disabled にした
- [x] disabled時はonClickを反応させない

## スクショ
### Before
<img width="203" alt="スクリーンショット 2021-04-07 12 25 56" src="https://user-images.githubusercontent.com/50824354/113806005-83fcb080-979c-11eb-88d6-bc6ce40a39fb.png">

### After
【`type: warning` 追加時】

![70235c60e9019a71d662ab3299686fe1](https://user-images.githubusercontent.com/50824354/113806025-8c54eb80-979c-11eb-84dd-fbe74c676539.gif)

2021-04-08 04:58 UTC, ryokosuge requested changes
確認お願いします

2021-04-08 04:58 UTC, ryokosuge commented on src/components/Icon/Icon.tsx
>  export const iconSize: { [key in IconSize]: number } = {
なんか変なcommit混ざってない？これはさっきあやひとがmasterにmergeしたやつだと思われる
しっかり変更点確認してくださいー

2021-04-08 04:58 UTC, ryokosuge commented on src/components/Icon/Icon.tsx
> +  close_circle: CloseCircleIcon,
これとか

2021-04-08 05:16 UTC, ryokosuge commented on src/components/MenuList/MenuList.tsx
> -  disabled?: boolean;
https://jsdoc.app/tags-deprecated.html
こいつ参考にして、disabledをdeprecatedにしておいてほしい

2021-04-08 05:17 UTC, ryokosuge commented on src/components/MenuList/MenuList.tsx
> -  disabled?: boolean;
disabledを消すと後方互換性が保てないので、残しておいてdeprecatedにしておく

2021-04-08 09:18 UTC, hirokikondo86 commented
後方互換性を保つためにもdisabled: booleanを優先。

2021-04-09 04:18 UTC, ryokosuge requested changes
確認よろしくー

2021-04-09 04:18 UTC, ryokosuge commented on src/components/MenuList/MenuList.tsx
> +    return contentTypeStyle["default"];
```
return contentTypeStyle.default;
```

で良さそう

2021-04-09 04:18 UTC, ryokosuge commented on src/components/MenuList/MenuList.tsx
> +   */
```
@deprecated since version 8.0.0
```

これだと「8.0.0以降deprecatedです」ってコメントにならない？
こういう時は「いずれ消します」くらいのコメントで問題ないよ
あとは「typeを使ってね」って促すようなコメントも欲しいかな

2021-04-09 08:59 UTC, ryokosuge approved these changes
LGTM 👍

2021-04-09 08:59 UTC, ryokosuge commented on src/components/MenuList/MenuList.tsx
> +   */
👍 
かっこいい

2021-04-12 00:59 UTC, merged