MenuにGroupを追加
voyagegroup/ingred-ui pull request #296
Opened 2021-04-09 09:18 UTC by hirokikondo86

2021-04-09 10:01 UTC, hirokikondo86 commented on src/components/MenuList/MenuList.tsx
> +        )}
render... みたいな関数を作るなら別コンポーネントに分けても良さそう…。

2021-04-09 10:03 UTC, hirokikondo86 commented
MenuListに依存しているコンポーネント（Menu, DropdownButton etc,）のcontentsの型情報も修正せねば。

2021-04-12 05:18 UTC, ryokosuge requested changes
確認よろしくー！

2021-04-12 05:18 UTC, ryokosuge commented on src/components/MenuList/MenuList.tsx
> +              {content.contents.map((content) => renderContent(content))}
```javascript
content.contents.map(renderContent)
```

で良さそう

2021-04-12 05:18 UTC, ryokosuge commented on src/components/MenuList/MenuList.tsx
> +        {contents.map((content: ContentProp | GroupContentProp) =>
ここだけ型が宣言されているのが違和感...
`contents` で宣言されてるからいらないと思うんだけど、残してる理由ってある？？

2021-04-12 05:18 UTC, ryokosuge commented on src/components/MenuList/MenuList.tsx
> +      }
空タイトルは許容していいんだっけ？？

2021-04-12 05:21 UTC, hirokikondo86 commented on src/components/MenuList/MenuList.tsx
> +        {contents.map((content: ContentProp | GroupContentProp) =>
ここ暗黙でanyが付いちゃうので明示的に指定してます！

2021-04-12 05:21 UTC, ryokosuge commented on src/components/MenuList/MenuList.tsx
> +        {contents.map((content: ContentProp | GroupContentProp) =>
なんでany着いちゃうんだ？

2021-04-12 05:22 UTC, ryokosuge commented on src/components/MenuList/MenuList.tsx
> +        {contents.map((content: ContentProp | GroupContentProp) =>
```
ContentProp[] | GroupContentProp[];
```

これじゃないの？

2021-04-12 05:24 UTC, hirokikondo86 commented on src/components/MenuList/MenuList.tsx
> +        {contents.map((content: ContentProp | GroupContentProp) =>
`contents: ContentProp[] | GroupContentProp[]`なので、`ContentProp | GroupContentProp`が付きそうなのですが、こんな感じになっちゃいますね…。
![image](https://user-images.githubusercontent.com/50824354/114344335-94e16380-9b9a-11eb-836c-78e9726d3d73.png)

2021-04-12 05:25 UTC, ryokosuge commented on src/components/MenuList/MenuList.tsx
> +        {contents.map((content: ContentProp | GroupContentProp) =>
あーじゃあ宣言の仕方変えた方がよさそう
型として健全じゃない

2021-04-12 05:27 UTC, ryokosuge commented on src/components/MenuList/MenuList.tsx
> +        {contents.map((content: ContentProp | GroupContentProp) =>
からGenericとか使ったらよさそう
型推論が効かないからから型指定するのは強引だと思う！

2021-04-12 05:27 UTC, hirokikondo86 commented on src/components/MenuList/MenuList.tsx
> +      }
グルーピングっていう観点で言うと、タイトルがないケースもあるのかなっていう風に思って、空タイトルも許容するようにしました！
因みに空にするとこんな感じになります。
![image](https://user-images.githubusercontent.com/50824354/114344636-27820280-9b9b-11eb-807a-9e6225da564e.png)

2021-04-12 05:28 UTC, ryokosuge commented on src/components/MenuList/MenuList.tsx
> +      }
そうそう、そういうのって野呂さんに確認とった？？

2021-04-12 05:28 UTC, hirokikondo86 commented on src/components/MenuList/MenuList.tsx
> +        {contents.map((content: ContentProp | GroupContentProp) =>
なるほど！👀変更します！

2021-04-12 05:29 UTC, hirokikondo86 commented on src/components/MenuList/MenuList.tsx
> +      }
取ってないです…！
ただ、確かにここはデザイン的な観点になってきますよね…。取ります…！

2021-04-12 05:32 UTC, hirokikondo86 commented on src/components/MenuList/MenuList.tsx
> +      }
@ryokosuge

2021-04-12 06:54 UTC, hirokikondo86 commented on src/components/MenuList/MenuList.tsx
> +        {contents.map((content: ContentProp | GroupContentProp) =>
よさそう👀

![image](https://user-images.githubusercontent.com/50824354/114352860-52725380-9ba7-11eb-998c-45958250ab51.png)

2021-04-12 06:57 UTC, ryokosuge approved these changes
LGTM 👍 
デザインは改めて @noronaoki さんに確認してもらってくださいませ！

2021-04-12 06:59 UTC, merged